"""init

Revision ID: 801699427929
Revises: 
Create Date: 2026-02-24 23:18:46.250462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801699427929'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('window_title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCTIVE', 'NEUTRAL', 'WASTEFUL', 'UNKNOWN', name='appcategory'), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_app_name'), 'activities', ['app_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_app_name'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
